### ISSUE TITLE
Typo in GPlot font properties

### ISSUE THREAD

**Issue by Ghirigoro** [jagracar/grafica.js#3]
The font property setters have a typo that causes an exception when setting font properties.

`GPlot.prototype.setFontName`, `GPlot.prototype.setFontColor`, `GPlot.prototype.setFontSize` and `GPlot.prototype.setFontProperties` all reference a variable named `maniLayer` when they probably should reference `mainLayer`

**Comment by jagracar** [comment]
Hi @Ghirigoro. Excuse me for taking me so long to fix these typos. 

These, together with other typos have been fixed with the pull request #4 by @xmalinov 

Thank you both for your help!
