### ISSUE TITLE
Error with new version from 2018-1-27

### ISSUE THREAD

**Issue by imorkovin** [jagracar/grafica.js#5]
I get error for 2d-plot:

Uncaught TypeError: Cannot read property 'elt' of undefined
    at new GPlot (grafica.min.js:1)
    at e.p.setup ((index):49)
    at e.<anonymous> (p5.min.js:5)
    at e.<anonymous> (p5.min.js:5)
    at new e (p5.min.js:5)
    at setup ((index):124)
    at e.<anonymous> (p5.min.js:5)
    at e.<anonymous> (p5.min.js:5)
    at new e (p5.min.js:5)
    at e (p5.min.js:4)

I rollback to version  grafica-0.1.0.min.js

**Comment by jagracar** [comment]
Sorry about that.

Can you add an example that reproduces the problem? 

I tested the examples that come with the lib and they run fine for me using the latest p5.min.js (January 19th, v0.6.0) and grafica.min.js (v0.3.0).

**Comment by imorkovin** [comment]
Hi, jagracar!
Try it
http://88.87.xx.xxx  

See index page code.
There are no  my plot. If I change  "grafica.min.js"  to "grafica-0.1.0.min.js" it's right.
 

>Понедельник, 29 января 2018, 13:23 +03:00 от Javier Graciá Carpio <notifications@github.com>:
>
>Sorry about that.
>Can you add an example that reproduces the problem?
>I tested the examples that come with the lib and they run fine for me using the latest p5.min.js (January 19th, v0.6.0) and grafica.min.js (v0.3.0).
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,

miasoft@mail.ru

**Comment by jagracar** [comment]
Hi again, 

That doesn't seem to be a valid link.  Can you post it again?

**Comment by imorkovin** [comment]
Is valid link. See attach


>Понедельник, 29 января 2018, 15:49 +03:00 от Javier Graciá Carpio <notifications@github.com>:
>
>Hi again,
>That doesn't seem to be a valid link.  Can you post it again?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,

miasoft@mail.ru

**Comment by jagracar** [comment]
I also cannot find any attachment.

**Comment by imorkovin** [comment]
may be ports 60xx and 80xx  is closed?
See html-code in index.html, please.



>Понедельник, 29 января 2018, 15:49 +03:00 от Javier Graciá Carpio <notifications@github.com>:
>
>Hi again,
>That doesn't seem to be a valid link.  Can you post it again?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,

miasoft@mail.ru

**Comment by xmalinov** [comment]
@imorkovin Hi, looks like you use an old version of P5
In your code 0.4.8 which is incompatible with current grafica.js build, try to update it to 0.5.10 or later

**Comment by imorkovin** [comment]
Thanks! You are right! Now it's work.
>  In your code 0.4.8 which is incompatible with current grafica.js build, try to update it to 0.5.10 or later

**Comment by jagracar** [comment]
Great that it works now. Thanks for using grafica!
